# Generated by Django 4.2.1 on 2023-06-06 15:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_cep_profile_cidade_profile_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('especie_animal', models.CharField(max_length=100)),
                ('raca_animal', models.CharField(max_length=100)),
                ('sexo_animal', models.CharField(max_length=100)),
                ('idade', models.IntegerField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
