# Generated by Django 4.2.1 on 2023-06-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
